# Spring properties
spring:
  application:
     name: catalog-service

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.80:1111/eureka/

# HTTP Server
server:
  port: 2222   # HTTP (Tomcat) port