spring:
    application:
        name: web-service #identify web-service
    freemaker:
        enable: false #ignore Eureka dashboard Freemaker templates
    thymeleaf:
        cache: true
        prefix: classpath:/web-server/
        
        
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.80:1111/eureka/

# HTTP Server
server:
  port: 3333   # HTTP (Tomcat) port